"""initial crm schema

Revision ID: 430ee4511375
Revises: 
Create Date: 2026-05-27 11:49:44.480588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '430ee4511375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS registro")
    op.execute("DROP TABLE IF EXISTS pratiche")
    op.execute("DROP TABLE IF EXISTS attivita")
    op.execute("DROP TABLE IF EXISTS clienti")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienti',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clienti_pkey'))
    )
    op.create_table('attivita',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.TEXT(), server_default=sa.text("'admin'::text"), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pratica_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titolo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('descrizione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stato', sa.TEXT(), server_default=sa.text("'da_fare'::text"), autoincrement=False, nullable=True),
    sa.Column('priorita', sa.TEXT(), server_default=sa.text("'media'::text"), autoincrement=False, nullable=True),
    sa.Column('scadenza', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clienti.id'], name=op.f('attivita_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pratica_id'], ['pratiche.id'], name=op.f('attivita_pratica_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('attivita_pkey'))
    )
    op.create_table('pratiche',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.TEXT(), server_default=sa.text("'admin'::text"), autoincrement=False, nullable=False),
    sa.Column('titolo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('valore_stimato', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fase', sa.TEXT(), server_default=sa.text("'nuovo_incarico'::text"), autoincrement=False, nullable=True),
    sa.Column('scadenza', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clienti.id'], name=op.f('pratiche_client_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pratiche_pkey'))
    )
    op.create_table('registro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), server_default=sa.text("'admin'::text"), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pratica_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attivita_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.TEXT(), server_default=sa.text("'nota'::text"), autoincrement=False, nullable=False),
    sa.Column('corpo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attivita_id'], ['attivita.id'], name=op.f('registro_attivita_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clienti.id'], name=op.f('registro_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pratica_id'], ['pratiche.id'], name=op.f('registro_pratica_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('registro_pkey'))
    )
    # ### end Alembic commands ###
